

server: 
  port: 8100

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9jfvwe87pjs867ino.mysql.rds.aliyuncs.com:3306/managerment?serverTimezone=GMT%2B8
    username: root
    password: Wuye2019 
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis: 
  mapper-locations:
  - classpath*:/mappers/**/*.xml
  type-aliases-package: com.neusoft.managerment.*
                          

logging:
  level:
    com.neusoft.managerment.*: debug
    

 